### ISSUE TITLE
Create Spinner Wheel

### ISSUE THREAD

**Issue by DrZimmer** [ElyCano/The_Dinner_Spinner#13]
Create Spinner Wheel with the 10 restaurant choices on it.

**Comment by DrZimmer** [comment]
option to choose one restaurant and that will be moved into restaurant history

**Comment by DrZimmer** [comment]
create button to actually spin the wheel

**Comment by DrZimmer** [comment]
clicking wheel will spin

**Comment by jamoore4579** [comment]
Wheel is working well
