### ISSUE TITLE
Find Resources- Ticket1

### ISSUE THREAD

**Issue by ElyCano** [ElyCano/The_Dinner_Spinner#2]
# Proposed Change

https://files.slack.com/files-pri/T02KLV26VU7-F02TF7H8QNN/page_1.png

https://files.slack.com/files-pri/T02KLV26VU7-F02TTSBELPK/page_2.png

https://files.slack.com/files-pri/T02KLV26VU7-F02U508694Y/page_3.png

# Why is this important

# Additional Context

**Comment by jamoore4579** [comment]
Not an issue
